server:
    port: 8080

spring:
    application:
        name: auth-gateway
    jpa:
        database: POSTGRESQL
        show-sql: true
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:postgresql://localhost:5432/pruebas
        username: usuariopruebas
        password: 1234
        driverClassName: org.postgresql.Driver
